import Layout from 'components/layout/Layout';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useSelector } from 'react-redux';
import { RootState } from 'store';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<Layout>
				<div>test</div>
			</Layout>
		</div>
	);
};

export default Home;
